# -*- coding: utf-8 -*-
"""LRproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgniy5jR-MVOw-pQXltek2Uq2nkqYToW
"""



import numpy as np
import pandas as pd

datafile=pd.read_csv('Social_Network_Ads.csv')
a=datafile.iloc[:,2:-1].values
b=datafile.iloc[:,-1].values

from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.25,random_state=0)
print(a_test)
print(a_train)
print(b_test)
print(b_train)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
a_train = sc.fit_transform(a_train)
a_test= sc.fit_transform(a_test)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(a_train, b_train)

b_pred = classifier.predict(b_test)
print(np.concatenate((b_pred.reshape(len(b_pred),1), b_test.reshape(len(b_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(b_test, b_pred)
print(cm)
accuracy_score(b_test, b_pred)